version: "2.4"

services:
  bot:
    image: far4599/telegram-lossless-media-bot
    mem_limit: 128m
    cpus: 2
    volumes:
      - bot-sessions-volume:/app/session
    env_file:
      - .env

volumes:
  bot-sessions-volume: